### ISSUE TITLE
Create background job to delete expired refresh tokens

### ISSUE THREAD

**Issue by yaninavoda** [project-studying-dotnet/Streetcode-Admin-March-01#277]

**Comment by NMarteniuk** [comment]
https://learn.microsoft.com/uk-ua/ef/core/dbcontext-configuration/#simple-dbcontext-initialization-with-new
https://learn.microsoft.com/en-us/dotnet/api/system.threading.timer.-ctor?view=net-8.0#system-threading-timer-ctor(system-threading-timercallback-system-object-system-timespan-system-timespan)

**Comment by NMarteniuk** [comment]
A background job in our app can be used for perfoming resource-intensiv tasks.
Another possibility to create background jobs is using "Hangfire" library.
Explain how it works:
In ServiceCollectionExtensions.cs file we have this code:
`        services.AddHangfire(config =>
        {
            config.UseSqlServerStorage(connectionString);
        });

        services.AddHangfireServer();`
In first line we add configuration to Hangfire: we add connection string to our database to create tables related with Hangfire.
In second line we add Hangfire server. It allows us use hangfire to create background jobs.
After building project you may see those tables:


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin-March-01/assets/117294549/7888c993-0264-4b72-9547-15278a367b8b)

So, you can make class with functions you need and make some functions in background using specification you prefer:


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin-March-01/assets/117294549/9a1bd601-1e7c-46b3-91ca-778ec881238b)
