### ISSUE TITLE
Deploy database to Azure

### ISSUE THREAD

**Issue by OlhaPivniuk** [project-studying-dotnet/Streetcode-Admin-March-01#282]
### **Description of task to person who takes this task:**
**1.** Create database in Azure portal
**2.** Add migrations to new database: 
    1) Add this connection string to your _secrets.json_ :
`"Server=tcp:streetcode-server.database.windows.net,1433;Initial Catalog=StreetcodeDB;Persist Security Info=False;User ID=streetcode-admin;Password=Qwer-1234;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"` ;
    2)Open Package Manager Console>DAL project and run command `Update-Database`;
    3)Build Project;
    4) After building open SQL Server Object Explorer and you must see :

![Image](https://github.com/project-studying-dotnet/Streetcode-Admin-March-01/assets/117294549/55139e54-decc-4461-bfaa-c41913c0cf6b)

### **Do this to your project works(to others)**:
1. Add this connection string to your _secrets.json_ :
`"Server=tcp:streetcode-server.database.windows.net,1433;Initial Catalog=StreetcodeDB;Persist Security Info=False;User ID=streetcode-admin;Password=Qwer-1234;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"`
2. Build project

**Comment by NMarteniuk** [comment]
Done
