### ISSUE TITLE
Create array from appsettings

### ISSUE THREAD

**Issue by OlhaPivniuk** [project-studying-dotnet/Streetcode-Admin-March-01#320]
На основі вашого secrets.json файлу, створіть наступний масив з усіма властивостями, щоб додати їх до Azure Configuration
Приклад:
[
  {
    "name": "<KeyName>:<PropertyName>",
    "value": "<data>",
    "slotSetting": false
  },
  {
    "name": "<KeyName>:<PropertyName>",
    "value": "<data>",
    "slotSetting": false
  },
]

[
  {
    "name": "EmailConfiguration:Port",
    "value": "465",
    "slotSetting": false
  },
  {
    "name": "EmailConfiguration:From",
    "value": "streetcodefeedback@gmail.com",
    "slotSetting": false
  },
]

**Comment by yaninavoda** [comment]
Done
